# Generated by Django 2.2.13 on 2020-07-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
