# Generated by Django 2.2.13 on 2020-07-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeAPI', '0002_auto_20200713_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='createddate',
            new_name='createdDate',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emp_code',
            new_name='empCode',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='fullname',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='updateddate',
            new_name='updatedDate',
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
